# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('bases', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jumbo', models.NullBooleanField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breads', models.CharField(max_length=10)),
                ('toasted', models.NullBooleanField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheeses', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Condiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiments', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwich_builder.Base')),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwich_builder.Bread')),
                ('cheeses', models.ManyToManyField(blank=True, default='No Cheese', to='sandwich_builder.Cheese')),
                ('condiments', models.ManyToManyField(blank=True, default='No Condiments', to='sandwich_builder.Condiment')),
            ],
            options={
                'verbose_name_plural': 'sandwiches',
            },
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sides', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='side',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='sandwich_builder.Side'),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='toppings',
            field=models.ManyToManyField(blank=True, default='No Toppings', to='sandwich_builder.Topping'),
        ),
    ]
