# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwich_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condiment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='side',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
